<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $table="products";
    public $timestamps=false;

    public function photo(){
        return $this->hasMany('App\ProductPhoto','product_id', 'id');
    }
    //Has many, erb mi hatin hamapatasxanum e shat tvyalner

    public function user(){
        return $this->belongsTo('App\Users', 'user_id', 'id');
    }
    //belongsto, erb mi hatin hamapatasxanum e mek tvyal

    public function rate(){
        return $this->hasMany('App\OrderDetails', 'product_id', 'id');
    }

//    public function getRate(){
//
//    }
//
//    public function __get($key)
//    {
//        return parent::__get($key); // TODO: Change the autogenerated stub
//    }
}
